import type { Title, Comment } from "./types";

export const MOCK_TITLES: Title[] = [
  {
    id: "mock-1",
    tmdb_id: 694,
    media_type: "movie",
    title: "The Shining",
    overview:
      "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.",
    poster_path: "/3tefOR9RVKCIAJRtLPVfXoGPqFa.jpg",
    backdrop_path: "/ugE5QFbnKlfYsLMxNJHMIhKJyGG.jpg",
    release_year: 1980,
    genres: ["Horror", "Thriller"],
    rating_avg: 8.4,
    rating_count: 312, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-2",
    tmdb_id: 948,
    media_type: "movie",
    title: "Halloween",
    overview:
      "Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to his home town.",
    poster_path: "/qVpCaBcnjZVTTXi3PEBbCCpT0tM.jpg",
    backdrop_path: "/xCuBPmmhGMy3WPHqTyijXvdaFpK.jpg",
    release_year: 1978,
    genres: ["Horror", "Thriller"],
    rating_avg: 7.6,
    rating_count: 289, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-3",
    tmdb_id: 419430,
    media_type: "movie",
    title: "Get Out",
    overview:
      "A young African-American man visits his white girlfriend's parents for the weekend, where his uneasiness about their reception of him grows into a horror film's worth of dread.",
    poster_path: "/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdrop_path: "/lplq0Kj22aYAIlXhxUEMBi2bQF3.jpg",
    release_year: 2017,
    genres: ["Horror", "Mystery", "Thriller"],
    rating_avg: 9.1,
    rating_count: 445, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-4",
    tmdb_id: 493922,
    media_type: "movie",
    title: "Hereditary",
    overview:
      "When the matriarch of the Graham family passes away, her daughter's family begins to unravel cryptic and terrifying secrets about their ancestry.",
    poster_path: "/tok2iHhkzYnElpM31gCjRaImJxp.jpg",
    backdrop_path: "/bXHJAuSMR4QnKVYZMTpBQMaTxMO.jpg",
    release_year: 2018,
    genres: ["Horror", "Drama", "Mystery"],
    rating_avg: 8.8,
    rating_count: 378, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-5",
    tmdb_id: 346364,
    media_type: "movie",
    title: "It",
    overview:
      "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster that emerges from the sewer every 27 years.",
    poster_path: "/9E2y5Q7WlCVNEhP5GkVComwyUB.jpg",
    backdrop_path: "/lRqOYZlSSPbQ4RLAGxPzxbdFUJn.jpg",
    release_year: 2017,
    genres: ["Horror", "Drama"],
    rating_avg: 7.3,
    rating_count: 521, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-6",
    tmdb_id: 530385,
    media_type: "movie",
    title: "Midsommar",
    overview:
      "A couple travel to Scandinavia to visit a rural hometown's fabled mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition.",
    poster_path: "/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    backdrop_path: "/y6lFjz3lCvVYLFnMVUGNFbBZKXk.jpg",
    release_year: 2019,
    genres: ["Horror", "Drama", "Mystery"],
    rating_avg: 7.9,
    rating_count: 267, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-7",
    tmdb_id: 4232,
    media_type: "movie",
    title: "Scream",
    overview:
      "A masked killer begins murdering the friends of Sidney Prescott, and the residents of the small town of Woodsboro start to suspect each other.",
    poster_path: "/s3WFiRyBFkMBvNFJF0SZOdEo1Fa.jpg",
    backdrop_path: "/cJBBFKBvPKqBgUMpJNiUvqwSvSC.jpg",
    release_year: 1996,
    genres: ["Horror", "Mystery"],
    rating_avg: 6.8,
    rating_count: 198, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-8",
    tmdb_id: 274,
    media_type: "movie",
    title: "The Silence of the Lambs",
    overview:
      "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    poster_path: "/rplLJ2hPcOQmkFhTqUte0MkosOe.jpg",
    backdrop_path: "/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg",
    release_year: 1991,
    genres: ["Crime", "Drama", "Thriller", "Horror"],
    rating_avg: 9.3,
    rating_count: 612, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-9",
    tmdb_id: 138843,
    media_type: "movie",
    title: "The Conjuring",
    overview:
      "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    poster_path: "/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    backdrop_path: "/nVRyd8hlg0ZLxBn9RaI7mUMQLnz.jpg",
    release_year: 2013,
    genres: ["Horror", "Thriller", "Mystery"],
    rating_avg: 7.5,
    rating_count: 334, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-10",
    tmdb_id: 621,
    media_type: "movie",
    title: "A Nightmare on Elm Street",
    overview:
      "Several Midwestern teenagers fall prey to Freddy Krueger, a disfigured midnight mangler who preys on the teenagers in their dreams.",
    poster_path: "/2RxinePSWsaGVFGVCBHnN6Msrs7.jpg",
    backdrop_path: "/vvoBPL1sC0IcqzCKirJi4PXoFt1.jpg",
    release_year: 1984,
    genres: ["Horror"],
    rating_avg: 7.1,
    rating_count: 276, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-11",
    tmdb_id: 66732,
    media_type: "tv",
    title: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one very strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    release_year: 2016,
    genres: ["Drama", "Sci-Fi & Fantasy", "Horror"],
    rating_avg: 8.6,
    rating_count: 489, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-12",
    tmdb_id: 1413,
    media_type: "tv",
    title: "American Horror Story",
    overview:
      "An anthology series that centers on different characters and locations, including a house with a murderous past, an insane asylum, a witch coven, and a freak show.",
    poster_path: "/vE5bSrHVXVCMnPfzLJYtSPBZ14q.jpg",
    backdrop_path: "/lqGBGRQU7mRkyf8IJfXWIVxz9ZE.jpg",
    release_year: 2011,
    genres: ["Drama", "Horror"],
    rating_avg: 6.9,
    rating_count: 301, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-13",
    tmdb_id: 77030,
    media_type: "tv",
    title: "The Haunting of Hill House",
    overview:
      "A group of siblings who grew up in the most famous haunted house in the country must finally confront the ghosts of their past.",
    poster_path: "/xbzPPR6dE0KXAOkVTqUNUFPCjQ7.jpg",
    backdrop_path: "/HuqHLPwSo9wAdZR3mHHhsgBUAqf.jpg",
    release_year: 2018,
    genres: ["Drama", "Horror"],
    rating_avg: 9.2,
    rating_count: 412, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-14",
    tmdb_id: 1402,
    media_type: "tv",
    title: "The Walking Dead",
    overview:
      "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
    poster_path: "/n7PBM9K5FanV9pS3KbXSMT8NTKB.jpg",
    backdrop_path: "/9MRz7MNloVMIvFmPiJkLPgViYNV.jpg",
    release_year: 2010,
    genres: ["Action & Adventure", "Drama", "Horror"],
    rating_avg: 7.4,
    rating_count: 567, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-15",
    tmdb_id: 132441,
    media_type: "tv",
    title: "Midnight Mass",
    overview:
      "A charismatic young priest arrives on a remote island and begins to perform what seem like miracles â€” but a more terrifying explanation lurks beneath.",
    poster_path: "/kP7t6RwGz2AvvTkvnI1uteEwHet.jpg",
    backdrop_path: "/nX2S4reBqONwCUMSZGRYhxPAOkS.jpg",
    release_year: 2021,
    genres: ["Drama", "Horror"],
    rating_avg: 8.9,
    rating_count: 356, critic_score: 80, tmdb_popularity: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "comment-1",
    user_id: "user-1",
    title_id: "mock-1",
    parent_id: null,
    content:
      "Kubrick's masterpiece. The Overlook Hotel feels alive and malevolent in a way few horror films achieve. REDRUM still gives me chills.",
    upvote_count: 42, downvote_count: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: { username: "CryptKeeper84", avatar_emoji: "💀", avatar_bg: "#0a0a0f" },
    replies: [
      {
        id: "comment-2",
        user_id: "user-2",
        title_id: "mock-1",
        parent_id: "comment-1",
        content: "Jack Nicholson is absolutely unhinged in the best way possible.",
        upvote_count: 18, downvote_count: 0,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        updated_at: new Date().toISOString(),
        profiles: { username: "GhostWatcher", avatar_emoji: "💀", avatar_bg: "#0a0a0f" },
        replies: [],
      },
    ],
  },
  {
    id: "comment-3",
    user_id: "user-3",
    title_id: "mock-1",
    parent_id: null,
    content:
      "The hedge maze finale is one of the most tense sequences in horror history. Shelley Duvall was robbed of award nominations.",
    upvote_count: 29, downvote_count: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date().toISOString(),
    profiles: { username: "NightStalker", avatar_emoji: "💀", avatar_bg: "#0a0a0f" },
    replies: [],
  },
];

export function isMockMode(): boolean {
  return !process.env.NEXT_PUBLIC_SUPABASE_URL;
}
